import os


class Config(object):
    NOTIFY_ADMIN_URL = os.environ['NOTIFY_ADMIN_URL']
    TWILIO_TEST_NUMBER = os.environ['TWILIO_TEST_NUMBER']
    TWILIO_ACCOUNT_SID = os.environ['TWILIO_ACCOUNT_SID']
    TWILIO_AUTH_TOKEN = os.environ['TWILIO_AUTH_TOKEN']
    FUNCTIONAL_TEST_EMAIL = os.environ['FUNCTIONAL_TEST_EMAIL']
    FUNCTIONAL_TEST_PASSWORD = os.environ['FUNCTIONAL_TEST_PASSWORD']
    EMAIL_FOLDER = 'notify'
    EMAIL_TIMEOUT = 120
