#!/usr/bin/env bash

set -eo pipefail

[ -n "$ENVIRONMENT" ] || (echo "ENVIRONMENT is not defined" && exit 1)

echo -n "" > docker.env

env_vars=(
    ENVIRONMENT
    BUILD_ID

    TEST_NUMBER
    FUNCTIONAL_TEST_EMAIL
    FUNCTIONAL_TEST_PASSWORD

    NOTIFY_ADMIN_URL
    NOTIFY_API_URL
    NOTIFY_SERVICE_API_KEY

    SERVICE_ID
    API_KEY

    FUNCTIONAL_TESTS_SERVICE_EMAIL
    FUNCTIONAL_TESTS_SERVICE_EMAIL_PASSWORD
    FUNCTIONAL_TESTS_SERVICE_ID
    FUNCTIONAL_TESTS_SERVICE_API_KEY
    FUNCTIONAL_TESTS_SERVICE_API_TEST_KEY
    FUNCTIONAL_TESTS_SERVICE_NAME
    FUNCTIONAL_TESTS_SERVICE_EMAIL_REPLY_TO
    FUNCTIONAL_TESTS_SERVICE_EMAIL_REPLY_TO_2
    FUNCTIONAL_TESTS_SERVICE_EMAIL_REPLY_TO_3
    FUNCTIONAL_TESTS_SERVICE_EMAIL_AUTH_ACCOUNT
    FUNCTIONAL_TESTS_ORGANISATION_ID
    FUNCTIONAL_TESTS_SERVICE_INBOUND_NUMBER

    JENKINS_BUILD_EMAIL_TEMPLATE_ID
    JENKINS_BUILD_SMS_TEMPLATE_ID
    JENKINS_BUILD_LETTER_TEMPLATE_ID

    PROVIDER_TEST_INBOUND_NUMBER

    DOCUMENT_DOWNLOAD_API_HOST
    DOCUMENT_DOWNLOAD_API_KEY

    MMG_INBOUND_SMS_USERNAME
    MMG_INBOUND_SMS_AUTH
)

for env_var in "${env_vars[@]}"; do
    if [ -n "${!env_var}" ]; then
      echo "${env_var}=${!env_var}" >> docker.env
    fi
done
